blank_issues_enabled: false
contact_links:

  - name: SFTPGo Commercial Support Request
    url: https://www.sftpgo.com/support
    about: >
        Commercial customers who pay for SFTPGo Support package can report their problems here.
        Those reports are prioritized over unpaid requests.

