blank_issues_enabled: false
contact_links:

  - name: SFTPGo Commercial Support Request
    url: https://www.sftpgo.com/support
    about: >
        Commercial customers who pay for SFTPGo Support package can report their problems here.
        Those reports are prioritized over unpaid requests.

  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.

  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
