name: Open Source Bug Report
description: >
  Bug reports only. We can't profile custom configuration help.
  If you need custom configuration help, see Commercial Support below
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Bug is defined as a crash, or critical error.
        It's important to keep your report as detailed as possible.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
       
