name: Open Source Bug Report
description: >
  Bug reports only. We can't profile custom configuration help.
  If you need custom configuration help, see Commercial Support below
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Bug is defined as a crash, or critical error.
        It's important to keep your report as detailed as possible.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
       
  - type: dropdown
    id: usecase
    attributes:
      label: What are you using SFTPGo for?
      description: We'd like to understand your SFTPGo usecase more
      multiple: true
      options:
        - Private user, home usecase (home backup/VPS)
        - Professional user, 1 person business
        - Small business (3-person firm with file exchange?)
        - Medium business
        - Enterprise
 
  - type: dropdown
    id: support
    attributes:
      label: Could we get in touch with you for SFTPGo research?
      description: We want you to become our champion in your company; we'd love to talk to your C-level execs to potentially consider sponsoring SFTPGo
      multiple: false
      options:
        - Yes
        - No
   
